# -*- coding: utf-8 -*-
"""Dashboard de Producción Agrícola 2025-2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pB05b7p0eFaA8WJfxWPBIVEvJGdAzctT
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import os
from PIL import Image

# Configuración inicial de la página
st.set_page_config(
    page_title="Resumen de Producción - Convento Viejo",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# Paleta de colores Convento Viejo / Minimalista
NAVY = '#001f3f'
PISTACHIO = '#93C572'

# Orden de calibre estándar (de mayor tamaño a menor)
CALIBER_ORDER = [
    '4J', '3J', '2J', 'J', 'XL', 'L',
    '30', '32', '36', '40', '44', '48', '52', '56', '60', '66', '72', '78', '84', '88', '98', '108'
]

# Datos de origen (Raw Data del PDF)
raw_data = [
    {"especie": "CEREZAS", "variedad": "TIP-TOP", "cuartel": "CRCHTTP21", "hectareas": 2.9, "cosechos": 7567, "exportacias": 5543, "cajas": 1205, "export_pct": 73.0, "calibres": {"4J": 0, "3J": 0, "2J": 79, "J": 54, "XL": 39, "L": 0}},
    {"especie": "CEREZAS", "variedad": "GABRIEL", "cuartel": "LOCHGAB21-A", "hectareas": 1.81, "cosechos": 5461, "exportacias": 5026, "cajas": 1629, "export_pct": 92.0, "calibres": {"4J": 14, "3J": 42, "2J": 37, "J": 6, "XL": 2, "L": 0}},
    {"especie": "CEREZAS", "variedad": "GABRIEL", "cuartel": "LOCHGAB21-B", "hectareas": 0.56, "cosechos": 1169, "exportacias": 1045, "cajas": 208, "export_pct": 89.0, "calibres": {"4J": 11, "3J": 40, "2J": 37, "J": 9, "XL": 3, "L": 0}},
    {"especie": "CEREZAS", "variedad": "LORENZ", "cuartel": "LOCHLOR21-A", "hectareas": 2.5, "cosechos": 5183, "exportacias": 4633, "cajas": 923, "export_pct": 89.0, "calibres": {"4J": 11, "3J": 40, "2J": 37, "J": 99, "XL": 3, "L": 0}},
    {"especie": "CEREZAS", "variedad": "LORENZ", "cuartel": "LOCHLOR21-B", "hectareas": 1.53, "cosechos": 3178, "exportacias": 2841, "cajas": 566, "export_pct": 89.0, "calibres": {"4J": 1, "3J": 40, "2J": 37, "J": 99, "XL": 3, "L": 0}},
    {"especie": "CEREZAS", "variedad": "LORENZ", "cuartel": "LOCHLOR21-C", "hectareas": 0.8, "cosechos": 1168, "exportacias": 1026, "cajas": 312, "export_pct": 88.0, "calibres": {"4J": 16, "3J": 47, "2J": 32, "J": 5, "XL": 0, "L": 0}},
    {"especie": "CEREZAS", "variedad": "LAPINS", "cuartel": "LOCHLPP18", "hectareas": 3.0, "cosechos": 38951, "exportacias": 37006, "cajas": 7337, "export_pct": 95.0, "calibres": {"4J": 16, "3J": 44, "2J": 35, "J": 4, "XL": 1, "L": 0}},
    {"especie": "CEREZAS", "variedad": "SANTINA", "cuartel": "LOCHXNA14", "hectareas": 4.4, "cosechos": 88412, "exportacias": 81632, "cajas": 16055, "export_pct": 92.0, "calibres": {"4J": 8, "3J": 31, "2J": 41, "J": 14, "XL": 6, "L": 1}},
    {"especie": "CEREZAS", "variedad": "SANTINA", "cuartel": "LOCHXNA21", "hectareas": 2.8, "cosechos": 40739, "exportacias": 38417, "cajas": 7704, "export_pct": 94.0, "calibres": {"4J": 9, "3J": 30, "2J": 43, "J": 13, "XL": 4, "L": 1}},
    {"especie": "CEREZAS", "variedad": "SANTINA", "cuartel": "LOCHXNA23", "hectareas": 3.0, "cosechos": 1242, "exportacias": 1118, "cajas": 158, "export_pct": 90.0, "calibres": {"4J": 10, "3J": 3, "2J": 37, "J": 37, "XL": 20, "L": 2}},
    {"especie": "DAMASCOS", "variedad": "MIRANDELLA", "cuartel": "CRAPFLP24", "hectareas": 9.24, "cosechos": 45798, "exportacias": 26583, "cajas": 4183, "export_pct": 58.0, "calibres": {"66": 0, "72": 0, "84": 3, "78": 0, "88": 22, "98": 23, "108": 52}},
    {"especie": "NECTARINES", "variedad": "CAKE BELLA", "cuartel": "LONEBEL24", "hectareas": 4.0, "cosechos": 49570, "exportacias": 40608, "cajas": 4325, "export_pct": 82.0, "calibres": {"30": 8, "32": 43, "36": 24, "40": 11, "44": 6, "48": 4, "52": 3, "56": 0, "60": 0}},
    {"especie": "NECTARINES", "variedad": "BORAL", "cuartel": "LONEBOR24", "hectareas": 4.0, "cosechos": 59975, "exportacias": 43550, "cajas": 5262, "export_pct": 73.0, "calibres": {"30": 0, "32": 2, "36": 15, "40": 18, "44": 20, "48": 10, "52": 8, "56": 15, "60": 11, "66": 6, "72": 3, "78": 0}},
    {"especie": "NECTARINES", "variedad": "CAKE DELICE", "cuartel": "LONEDEL24", "hectareas": 4.0, "cosechos": 78680, "exportacias": 64922, "cajas": 6984, "export_pct": 83.0, "calibres": {"30": 3, "32": 33, "36": 25, "40": 28, "44": 30, "48": 17, "52": 12, "56": 6, "60": 4, "66": 1, "72": 1, "78": 0}}
]

df = pd.DataFrame(raw_data)

# Función auxiliar de formateo con separador de miles en punto
def fmt_int(value):
    return f"{value:,.0f}".replace(",", ".")

def fmt_dec(value):
    return f"{value:,.1f}".replace(",", "X").replace(".", ",").replace("X", ".")

# Estilos CSS personalizados para preservar el look minimalista blanco, azul marino y pistacho
st.markdown(f"""
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap');
        html, body, [class*="css"] {{
            font-family: 'Inter', sans-serif;
            background-color: #FFFFFF !important;
        }}
        .kpi-card {{
            border-left: 4px solid {PISTACHIO};
            padding: 10px 0px 10px 20px;
            margin-bottom: 25px;
        }}
        .kpi-title {{
            font-size: 10px;
            color: #94a3b8;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.15em;
            margin-bottom: 4px;
        }}
        .kpi-value {{
            font-size: 34px;
            font-weight: 300;
            color: {NAVY};
            line-height: 1.1;
        }}
        .kpi-unit {{
            font-size: 11px;
            font-weight: bold;
            color: #cbd5e1;
            text-transform: uppercase;
        }}
    </style>
""", unsafe_allow_html=True)

# Encabezado con Logo y Título
col_logo, col_title = st.columns([1, 4])

with col_logo:
    logo_path = "LogoConventoViejo-01.jpg"
    if os.path.exists(logo_path):
        img = Image.open(logo_path)
        st.image(img, use_column_width=False, width=150)
    else:
        # Fallback decorativo elegante si el logo no carga localmente
        st.markdown(f"<div style='background-color: {NAVY}; width:60px; height:60px; border-radius:4px;'></div>", unsafe_allow_html=True)

with col_title:
    st.markdown(f"""
        <div style='padding-top: 10px;'>
            <h1 style='color: {NAVY}; font-size: 28px; font-weight: 300; text-transform: uppercase; margin:0;'>
                Resumen de <span style='font-weight: 800;'>Producción</span>
            </h1>
            <p style='color: {PISTACHIO}; font-weight: bold; font-size: 13px; text-transform: uppercase; letter-spacing: 0.15em; margin:0;'>
                Temporada 2025-2026
            </p>
        </div>
    """, unsafe_allow_html=True)

st.markdown("<hr style='margin-top: 20px; margin-bottom: 30px; border-color: #f1f5f9;' />", unsafe_allow_html=True)

# Filtros Interactivos actualizables dinámicamente
filter_col1, filter_col2 = st.columns(2)

with filter_col1:
    especies_list = ["TODAS"] + sorted(list(df['especie'].unique()))
    selected_especie = st.selectbox("Especie", especies_list)

# Filtrar las variedades dependientes de la especie seleccionada
if selected_especie == "TODAS":
    variedades_disponibles = sorted(list(df['variedad'].unique()))
else:
    variedades_disponibles = sorted(list(df[df['especie'] == selected_especie]['variedad'].unique()))

with filter_col2:
    variedades_list = ["TODAS"] + variedades_disponibles
    selected_variedad = st.selectbox("Variedad", variedades_list)

# Aplicar filtros al DataFrame
filtered_df = df.copy()
if selected_especie != "TODAS":
    filtered_df = filtered_df[filtered_df['especie'] == selected_especie]
if selected_variedad != "TODAS":
    filtered_df = filtered_df[filtered_df['variedad'] == selected_variedad]

# Cálculos de Métricas KPIs
total_ha = filtered_df['hectareas'].sum()
total_cosecha = filtered_df['cosechos'].sum()
total_export = filtered_df['exportacias'].sum()
total_cajas = filtered_df['cajas'].sum()
avg_export_pct = (total_export / total_cosecha * 100) if total_cosecha > 0 else 0
kg_por_ha = (total_cosecha / total_ha) if total_ha > 0 else 0

# Fila de KPIs
kpi_cols = st.columns(4)

with kpi_cols[0]:
    st.markdown(f"""
        <div class="kpi-card">
            <div class="kpi-title">Superficie Total</div>
            <div class="kpi-value">{fmt_dec(total_ha)} <span class="kpi-unit">ha</span></div>
        </div>
    """, unsafe_allow_html=True)

with kpi_cols[1]:
    st.markdown(f"""
        <div class="kpi-card" style="border-left-color: {NAVY};">
            <div class="kpi-title" style="color: {NAVY};">Cosecha Total</div>
            <div class="kpi-value">{fmt_int(total_cosecha)} <span class="kpi-unit">kg</span></div>
        </div>
    """, unsafe_allow_html=True)

with kpi_cols[2]:
    st.markdown(f"""
        <div class="kpi-card">
            <div class="kpi-title">Eficiencia</div>
            <div class="kpi-value">{avg_export_pct:.1f}%</div>
        </div>
    """, unsafe_allow_html=True)

with kpi_cols[3]:
    st.markdown(f"""
        <div class="kpi-card">
            <div class="kpi-title">Cajas Exportadas</div>
            <div class="kpi-value">{fmt_int(total_cajas)} <span class="kpi-unit">cajas</span></div>
        </div>
    """, unsafe_allow_html=True)

# Procesamiento de datos para Gráficas
# 1. Agrupamiento por Variedad
grouped_df = filtered_df.groupby(['especie', 'variedad']).agg({
    'hectareas': 'sum',
    'cosechos': 'sum',
    'exportacias': 'sum',
    'cajas': 'sum'
}).reset_index()
grouped_df['export_pct'] = (grouped_df['exportacias'] / grouped_df['cosechos'] * 100).fillna(0)
grouped_df['rendimiento'] = (grouped_df['cosechos'] / grouped_df['hectareas']).fillna(0)
grouped_df = grouped_df.sort_values(by='cosechos', ascending=False)

# 2. Distribución de Calibres ponderada
combined_calibers = {}
total_weight = filtered_df['cosechos'].sum()

for _, row in filtered_df.iterrows():
    for caliber, pct in row['calibres'].items():
        weighted_val = (pct / 100.0) * row['cosechos']
        combined_calibers[caliber] = combined_calibers.get(caliber, 0) + weighted_val

caliber_data = []
for caliber, val in combined_calibers.items():
    pct = (val / total_weight * 100) if total_weight > 0 else 0
    caliber_data.append({"Calibre": caliber, "Porcentaje": pct})

caliber_df = pd.DataFrame(caliber_data)

if not caliber_df.empty:
    caliber_df['order'] = caliber_df['Calibre'].map(lambda x: CALIBER_ORDER.index(x) if x in CALIBER_ORDER else 999)
    caliber_df = caliber_df.sort_values('order').drop(columns=['order'])

# Sección de Gráficos (Columnas 2:1)
graph_col1, graph_col2 = st.columns([2, 1])

with graph_col1:
    st.markdown(f"""
        <div style="display:flex; align-items:center; gap:8px; margin-bottom: 20px;">
            <div style="width: 6px; height: 6px; border-radius: 50%; background-color: {PISTACHIO};"></div>
            <span style="font-size:11px; font-weight:bold; text-transform:uppercase; color:#94a3b8; letter-spacing:0.1em;">
                Exportación: Volumen (kg) y Eficiencia (%)
            </span>
        </div>
    """, unsafe_allow_html=True)

    fig_export = make_subplots(specs=[[{"secondary_y": True}]])

    # Barra de Volumen de Exportación
    fig_export.add_trace(
        go.Bar(
            x=grouped_df['variedad'],
            y=grouped_df['exportacias'],
            name="Kilos Exportados",
            marker_color=NAVY,
            hovertemplate="<b>%{x}</b><br>Kilos Exportados: %{y:,.0f} kg<extra></extra>",
            width=0.35
        ),
        secondary_y=False
    )

    # Línea de Eficiencia % (Sin decimales en tooltip)
    fig_export.add_trace(
        go.Scatter(
            x=grouped_df['variedad'],
            y=grouped_df['export_pct'],
            name="Eficiencia %",
            mode="lines+markers",
            line=dict(color=PISTACHIO, width=3),
            marker=dict(size=8, color=PISTACHIO),
            hovertemplate="<b>%{x}</b><br>Eficiencia: %{y:.0f}%<extra></extra>"
        ),
        secondary_y=True
    )

    fig_export.update_layout(
        plot_bgcolor='white',
        paper_bgcolor='white',
        legend=dict(orientation="h", yanchor="bottom", y=1.05, xanchor="right", x=1, font=dict(size=10, color='#475569')),
        margin=dict(l=0, r=0, t=10, b=0),
        xaxis=dict(showgrid=False, linecolor='#e2e8f0', tickfont=dict(color='#94a3b8', size=10)),
        yaxis=dict(showgrid=True, gridcolor='#f1f5f9', linecolor='rgba(0,0,0,0)', tickfont=dict(color='#94a3b8', size=10)),
        yaxis2=dict(showgrid=False, linecolor='rgba(0,0,0,0)', tickfont=dict(color=PISTACHIO, size=10), ticksuffix="%"),
        height=320,
    )
    st.plotly_chart(fig_export, use_container_width=True, config={'displayModeBar': False})

with graph_col2:
    st.markdown(f"""
        <div style="display:flex; align-items:center; gap:8px; margin-bottom: 20px;">
            <div style="width: 6px; height: 6px; border-radius: 50%; background-color: {NAVY};"></div>
            <span style="font-size:11px; font-weight:bold; text-transform:uppercase; color:#94a3b8; letter-spacing:0.1em;">
                Distribución de Calibres (%)
            </span>
        </div>
    """, unsafe_allow_html=True)

    if not caliber_df.empty:
        fig_caliber = go.Figure()
        fig_caliber.add_trace(
            go.Bar(
                x=caliber_df['Calibre'],
                y=caliber_df['Porcentaje'],
                marker_color=[NAVY if i % 2 == 0 else PISTACHIO for i in range(len(caliber_df))],
                hovertemplate="Calibre %{x}<br>Porcentaje: %{y:.1f}%<extra></extra>",
                width=0.45
            )
        )
        fig_caliber.update_layout(
            plot_bgcolor='white',
            paper_bgcolor='white',
            margin=dict(l=0, r=0, t=10, b=0),
            xaxis=dict(showgrid=False, linecolor='#e2e8f0', tickfont=dict(color='#475569', size=11, bold=True)),
            yaxis=dict(showgrid=True, gridcolor='#f1f5f9', linecolor='rgba(0,0,0,0)', tickfont=dict(color='#94a3b8', size=10)),
            height=320
        )
        st.plotly_chart(fig_caliber, use_container_width=True, config={'displayModeBar': False})
    else:
        st.info("No hay calibres disponibles para los filtros seleccionados.")

# Detalle Consolidado por Variedad (Tabla Estilizada HTML)
st.markdown("<br>", unsafe_allow_html=True)
st.markdown(f"""
    <div style="display:flex; align-items:center; gap:8px; margin-bottom: 20px;">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="{PISTACHIO}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
        <span style="font-size:11px; font-weight:bold; text-transform:uppercase; color:#94a3b8; letter-spacing:0.1em;">
            Detalle Consolidado por Variedad
        </span>
    </div>
""", unsafe_allow_html=True)

# Armar la tabla en HTML para un diseño idéntico al solicitado (con barras de progreso y colores limpios)
table_html = f"""
<table style="width: 100%; border-collapse: collapse; font-family: sans-serif; background-color: #FFFFFF;">
    <thead>
        <tr style="text-transform: uppercase; font-size: 10px; font-weight: bold; letter-spacing: 0.1em; background-color: #f8fafc; border-bottom: 2px solid #e2e8f0; color: {NAVY};">
            <th style="padding: 16px; text-align: left;">Variedad</th>
            <th style="padding: 16px; text-align: right;">Superficie</th>
            <th style="padding: 16px; text-align: right;">Cosecha (kg)</th>
            <th style="padding: 16px; text-align: right; color: {NAVY};">Export. (kg)</th>
            <th style="padding: 16px; text-align: right; color: {PISTACHIO};">Export. (cajas)</th>
            <th style="padding: 16px; text-align: right;">Eficiencia</th>
            <th style="padding: 16px; text-align: right;">Rendimiento</th>
        </tr>
    </thead>
    <tbody style="font-size: 13.5px; color: #334155;">
"""

for _, row in grouped_df.iterrows():
    pct = row['export_pct']
    table_html += f"""
        <tr style="border-bottom: 1px solid #f1f5f9; transition: background-color 0.2s;">
            <td style="padding: 16px; text-align: left; font-weight: bold; color: #1e293b;">
                <span style="font-size: 10px; color: #94a3b8; display: block; font-weight: 500; margin-bottom: 2px;">{row['especie']}</span>
                {row['variedad']}
            </td>
            <td style="padding: 16px; text-align: right; color: #64748b;">{fmt_dec(row['hectareas'])} ha</td>
            <td style="padding: 16px; text-align: right; font-weight: 600; color: #334155;">{fmt_int(row['cosechos'])}</td>
            <td style="padding: 16px; text-align: right; font-weight: 600; color: {NAVY};">{fmt_int(row['exportacias'])}</td>
            <td style="padding: 16px; text-align: right; font-weight: bold; color: {PISTACHIO}; background-color: rgba(147, 197, 114, 0.04);">{fmt_int(row['cajas'])}</td>
            <td style="padding: 16px; text-align: right; font-weight: bold; color: {NAVY};">
                <div style="display: inline-flex; align-items: center; gap: 8px;">
                    <div style="width: 60px; height: 5px; background-color: #f1f5f9; border-radius: 999px; overflow: hidden; display: inline-block;">
                        <div style="width: {pct}%; height: 100%; background-color: {PISTACHIO};"></div>
                    </div>
                    <span>{pct:.1f}%</span>
                </div>
            </td>
            <td style="padding: 16px; text-align: right; color: #94a3b8; font-style: italic;">{fmt_int(row['rendimiento'])} kg/ha</td>
        </tr>
    """

# Fila de Totales Consolidados
if len(grouped_df) > 1:
    table_html += f"""
        <tr style="background-color: #f8fafc; font-weight: bold; font-size: 13px; color: {NAVY}; border-top: 2px solid #e2e8f0;">
            <td style="padding: 16px; text-align: left; letter-spacing: 0.05em;">TOTALES</td>
            <td style="padding: 16px; text-align: right;">{fmt_dec(total_ha)} ha</td>
            <td style="padding: 16px; text-align: right;">{fmt_int(total_cosecha)} kg</td>
            <td style="padding: 16px; text-align: right;">{fmt_int(total_export)} kg</td>
            <td style="padding: 16px; text-align: right; color: {PISTACHIO};">{fmt_int(total_cajas)} cajas</td>
            <td style="padding: 16px; text-align: right;">{avg_export_pct:.1f}%</td>
            <td style="padding: 16px; text-align: right; color: #94a3b8;">{fmt_int(kg_por_ha)} kg/ha</td>
        </tr>
    """

table_html += "</tbody></table>"

st.markdown(table_html, unsafe_allowed_html=True)
